export const mockUsers = [
  {
    id: "1",
    username: "johndoe",
    displayName: "John Doe",
    avatar: "https://images.unsplash.com/photo-1582836985321-7a3f82fb6f3f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    bio: "Film enthusiast & bookworm. Living for those cinematic moments.",
    followers: 1243,
    following: 892,
    isCurrentUser: true,
  },
  {
    id: "2",
    username: "sarahconnor",
    displayName: "Sarah Connor",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400",
    bio: "Sci-fi lover. Reading between the lines.",
    followers: 856,
    following: 423,
    isCurrentUser: false,
  },
  {
    id: "3",
    username: "mikethomas",
    displayName: "Mike Thomas",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    bio: "Cinephile. Horror & thriller fan.",
    followers: 2104,
    following: 634,
    isCurrentUser: false,
  },
];

export const mockContent = [
  {
    id: "1",
    type: "movie",
    title: "Blade Runner 2049",
    year: 2017,
    poster: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=600",
    director: "Denis Villeneuve",
    genres: ["Sci-Fi", "Thriller"],
    duration: "164 min",
    rating: 8.9,
    totalRatings: 15423,
    summary:
      "A young blade runner's discovery of a long-buried secret leads him to track down former blade runner Rick Deckard, who's been missing for thirty years.",
  },
  {
    id: "2",
    type: "movie",
    title: "The Grand Budapest Hotel",
    year: 2014,
    poster: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=600",
    director: "Wes Anderson",
    genres: ["Comedy", "Drama"],
    duration: "99 min",
    rating: 8.5,
    totalRatings: 12893,
    summary:
      "The adventures of Gustave H, a legendary concierge at a famous European hotel, and Zero Moustafa, the lobby boy who becomes his most trusted friend.",
  },
  {
    id: "3",
    type: "book",
    title: "Dune",
    year: 1965,
    poster: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600",
    author: "Frank Herbert",
    genres: ["Sci-Fi", "Fantasy"],
    pages: "688 pages",
    rating: 9.2,
    totalRatings: 23451,
    summary:
      "Set in the distant future amidst a feudal interstellar society, this epic novel follows young Paul Atreides and his family as they navigate political intrigue on the desert planet Arrakis.",
  },
  {
    id: "4",
    type: "movie",
    title: "Parasite",
    year: 2019,
    poster: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600",
    director: "Bong Joon Ho",
    genres: ["Thriller", "Drama"],
    duration: "132 min",
    rating: 8.8,
    totalRatings: 18765,
    summary:
      "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
  },
  {
    id: "5",
    type: "book",
    title: "The Midnight Library",
    year: 2020,
    poster: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600",
    author: "Matt Haig",
    genres: ["Fiction", "Fantasy"],
    pages: "304 pages",
    rating: 8.3,
    totalRatings: 9876,
    summary:
      "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.",
  },
];

export const mockActivities = [
  {
    id: "1",
    user: mockUsers[1],
    action: "rated a movie",
    content: mockContent[0],
    rating: 9,
    timestamp: "3 hours ago",
    review:
      "Absolutely stunning visuals and a hauntingly beautiful score. Villeneuve crafted a masterpiece that honors the original while standing on its own.",
    likes: 42,
    comments: 8,
  },
  {
    id: "2",
    user: mockUsers[2],
    action: "reviewed a book",
    content: mockContent[2],
    rating: 10,
    timestamp: "5 hours ago",
    review:
      "Herbert's world-building is unparalleled. The political intrigue, ecology, and philosophy woven throughout make this a timeless classic. A must-read for any sci-fi fan.",
    likes: 67,
    comments: 15,
  },
  {
    id: "3",
    user: mockUsers[1],
    action: "added to watchlist",
    content: mockContent[3],
    timestamp: "8 hours ago",
    likes: 12,
    comments: 3,
  },
  {
    id: "4",
    user: mockUsers[2],
    action: "rated a movie",
    content: mockContent[1],
    rating: 8,
    timestamp: "12 hours ago",
    review: "Wes Anderson at his finest. Every frame is a painting, and the story is both whimsical and heartwarming.",
    likes: 38,
    comments: 6,
  },
  {
    id: "5",
    user: mockUsers[1],
    action: "reviewed a book",
    content: mockContent[4],
    rating: 7,
    timestamp: "1 day ago",
    review:
      "A touching exploration of regret and second chances. While the concept is fascinating, the execution felt a bit repetitive at times.",
    likes: 29,
    comments: 11,
  },
  {
    id: "6",
    user: mockUsers[2],
    action: "added to custom list",
    content: mockContent[3],
    timestamp: "1 day ago",
    likes: 18,
    comments: 2,
  },
  {
    id: "7",
    user: mockUsers[1],
    action: "rated a book",
    content: mockContent[2],
    rating: 9,
    timestamp: "2 days ago",
    review: "Incredible sci-fi epic that still holds up decades later. The attention to detail in the world-building is remarkable.",
    likes: 54,
    comments: 9,
  },
];

export const mockComments = [
  {
    id: "1",
    user: mockUsers[1],
    text: "I couldn't agree more! The cinematography alone makes this worth watching.",
    timestamp: "2 hours ago",
  },
  {
    id: "2",
    user: mockUsers[2],
    text: "Have you read the book? Curious how it compares.",
    timestamp: "4 hours ago",
  },
  {
    id: "3",
    user: mockUsers[0],
    text: "Yes! The book expands on many concepts. Both are masterpieces in their own right.",
    timestamp: "3 hours ago",
  },
];